# Generated by Django 4.2.6 on 2026-06-12 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=100)),
                ('credits', models.IntegerField(default=3)),
                ('schedule_json', models.JSONField(blank=True, default=dict)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.customuser')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_number', models.IntegerField(default=1)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('lecture_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('venue_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('venue_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('allowed_radius', models.IntegerField(default=50, help_text='Radius in meters')),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('qr_expiry_minutes', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.course')),
            ],
            options={
                'db_table': 'lectures',
                'ordering': ['-lecture_date', 'start_time'],
                'indexes': [models.Index(fields=['course', 'lecture_date'], name='lectures_course__b945f4_idx'), models.Index(fields=['lecture_date'], name='lectures_lecture_b907d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='active', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.customuser')),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date'],
                'indexes': [models.Index(fields=['student', 'course'], name='enrollments_student_9c8d9e_idx'), models.Index(fields=['status'], name='enrollments_status_dfab18_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code'], name='courses_course__5da9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['lecturer'], name='courses_lecture_d85c05_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['academic_year'], name='courses_academi_638de3_idx'),
        ),
    ]
