# Generated by Django 4.2.6 on 2026-07-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='qr_close_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='qr_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='qr_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_qr_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='qr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['qr_status'], name='lectures_qr_stat_2fe9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['qr_generated_at'], name='lectures_qr_gene_6b829c_idx'),
        ),
    ]
