# Generated by Django 4.2.6 on 2026-06-12 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_verified', models.BooleanField(default=False)),
                ('distance_from_venue', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in meters', max_digits=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.lecture')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.customuser')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeolocationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=10, null=True)),
                ('distance_from_venue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('failed', 'Failed'), ('suspicious', 'Suspicious')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geolocation_logs', to='attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocation_logs', to='accounts.customuser')),
            ],
            options={
                'db_table': 'geolocation_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'timestamp'], name='geolocation_student_a1090d_idx'), models.Index(fields=['verification_status'], name='geolocation_verific_938507_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('student', 'Student'), ('course', 'Course'), ('department', 'Department')], max_length=20)),
                ('report_title', models.CharField(max_length=255)),
                ('filters', models.JSONField(default=dict)),
                ('file_path', models.FileField(upload_to='reports/')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='accounts.customuser')),
            ],
            options={
                'db_table': 'attendance_reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type'], name='attendance__report__0dc53d_idx'), models.Index(fields=['generated_at'], name='attendance__generat_512fe7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['lecture', 'student'], name='attendance_lecture_e7dd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['timestamp'], name='attendance_timesta_d0ec2c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student'], name='attendance_student_5b1d70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lecture', 'student')},
        ),
    ]
