# Generated by Django 4.2.6 on 2026-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
