# Generated by Django 4.2.6 on 2026-07-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lecture_qr_close_reason_lecture_qr_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_alter_attendancereport_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAttempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], max_length=20)),
                ('reason', models.CharField(choices=[('marked', 'Marked'), ('already_marked', 'Already Marked'), ('invalid_qr', 'Invalid QR'), ('expired_qr', 'Expired QR'), ('closed_qr', 'Closed QR'), ('missing_location', 'Missing Location'), ('invalid_location', 'Invalid Location'), ('poor_accuracy', 'Poor Accuracy'), ('outside_radius', 'Outside Radius'), ('lecturer_location_missing', 'Lecturer Location Missing'), ('unauthorized', 'Unauthorized')], max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_from_venue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allowed_radius', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='attendance.attendance')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attempts', to='courses.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'timestamp'], name='attendance__student_7857f0_idx'), models.Index(fields=['lecture', 'timestamp'], name='attendance__lecture_b4cbfe_idx'), models.Index(fields=['status'], name='attendance__status_fbe7c4_idx'), models.Index(fields=['reason'], name='attendance__reason_046959_idx')],
            },
        ),
    ]
